### ISSUE TITLE
Activity 1: Your First Caption

### ISSUE THREAD

**Issue by githubteacher** [githubschool/jon-snow-knows-everything#2]
Using the API, I have just created a file with a random octocat for you to caption. In this activity, we will learn how to make changes to files in our GitHub repository.

- [ ] @AdamAnSubtractM
- [ ] @TheLandoCal
- [ ] @aparnarustagi1
- [ ] @brendanlafond
- [ ] @chiru0826
- [ ] @ckingery15
- [ ] @dagenester
- [ ] @inaroquet
- [ ] @jadavis86
- [ ] @jclark0714
- [ ] @jcumblidge
- [ ] @jekwesco
- [ ] @jrosser78
- [ ] @keith-patel
- [ ] @mbianchiniwesco
- [ ] @mbouxsein24
- [ ] @rafaelnavarrowesco
- [ ] @rsfierst
- [ ] @rwnfoo
- [ ] @Clobbster
- [ ] @SDandeWesco

**Comment by rwnfoo** [comment]
JON-123
